name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: docker://continuumio/anaconda3:2019.07
      - name: Build with Maven
        run: mvn verify -D DOCKER_ENGINE=127.0.0.1
